export const errors = {
    failedToChangePassword: 'Failed to change password',
    failedToCreateToken: 'Failed to create token',
    failedToLogout: 'Failed to log out',
    failedToRefreshToken: 'Failed to refresh token',
    failedToRegisterUser: 'Failed to register user',
    failedToSendEmail: 'Failed to send email',
    failedToSendEmailAndDeleteUser:
        'Failed to send email and delete user afterwards',
    failedToSetPassword: 'Failed to set password',
    failedToUpdateUser: 'Failed to update user',
    invalidOldPassword: 'The old password is invalid',
    invalidUserOrPassword: 'Invalid user or password',
    invalidEmailConfirmationToken: 'Invalid email confirmation token',
    missingAccessToken: 'Missing access token',
    missingPublicFaunaKey: 'missing publicFaunaKey',
    missingUserRef: 'Missing user ref',
    passwordAlreadyInUse: 'The new password is already in use',
    userAlreadyExists: 'User already exists',
    userDoesNotExist: 'User does not exist',
};
