export const errors = {
    failedToChangePassword: 'Failed to change password',
    failedToCreateToken: 'Failed to create token',
    failedToLogout: 'Failed to log out',
    failedToRefreshToken: 'Failed to refresh token',
    failedToRegisterUser: 'Failed to register user',
    failedToSendEmail: 'Failed to send email',
    failedToSendEmailAndDeleteUser:
        'Failed to send email and delete user afterwards',
    failedToSetPassword: 'Failed to set password',
    failedToUpdateUser: 'Failed to update user',
    invalidOldPassword: 'The old password is invalid',
    invalidEmailOrPassword: 'Invalid email or password',
    invalidEmailConfirmationToken: 'Invalid email confirmation token',
    invalidUsernameOrPassword: 'Invalid username or password',
    invalidEmailOrSecret: 'Invalid email or secret',
    missingAccessToken: 'Missing access token',
    missingPublicFaunaKey: 'Missing publicFaunaKey',
    missingUserRef: 'Missing user ref',
    passwordAlreadyInUse: 'New password is already in use',
    userAlreadyExists: 'User already exists',
    userDoesNotExist: 'User does not exist',
    unknownServerError: 'Unknown server error',
};
