export const errors = {
    failedToChangePassword: 'Failed to change password',
    failedToCreateToken: 'Failed to create token',
    failedToLogout: 'Failed to log out',
    failedToRefreshToken: 'Failed to refresh token',
    failedToRegisterUser: 'Failed to register user',
    failedToSendEmail: 'Failed to send email',
    failedToSendEmailAndDeleteUser:
        'Failed to send email and delete user afterwards',
    failedToSetPassword: 'Failed to set password',
    failedToUpdateUser: 'Failed to update user',
    invalidEmailConfirmationToken: 'Invalid email confirmation token',
    invalidEmailOrPassword: 'Invalid email or password',
    invalidEmailOrSecret: 'Invalid email or secret',
    invalidOldPassword: 'The old password is invalid',
    invalidUsernameOrPassword: 'Invalid username or password',
    missingAccessToken: 'Missing access token',
    missingAdminKey: 'Missing admin key',
    missingEmailAndUserID: 'You must provide either an email or userID',
    missingPublicFaunaKey: 'Missing public Fauna key',
    missingSecret: 'Missing secret',
    missingUserRef: 'Missing user ref',
    passwordAlreadyInUse: 'New password is already in use',
    unknownServerError: 'Unknown server error',
    userAlreadyExists: 'User already exists',
    userDoesNotExist: 'User does not exist',
};
